### ISSUE TITLE
ScrollIntoView export issue

### ISSUE THREAD

**Issue by rendyandika28** [privy-open-source/design-system#1388]
**Describe the bug**
When i try to install persona on Nuxt@3.12.4, i found some syntaxerror with message: Uncaught SyntaxError: The requested module '/_nuxt/node_modules/scroll-into-view/scrollIntoView.js?v=c0b770a2' does not provide an export named 'default'

**To Reproduce**
1. Do manual installation
2. Run project with yarn (i haven't try on other package manager)
3. See error _Uncaught SyntaxError: The requested module '/_nuxt/node_modules/scroll-into-view/scrollIntoView.js?v=c0b770a2' does not provide an export named 'default'_ and some of the component that i use didn't works, for example when i use Dropdown, the popup option not showing, and Collapse component didn't works too.

**Expected behavior**
i can use the component normally (the popup option or animation works fine)

**Screenshots**
<img width="716" alt="image" src="https://github.com/user-attachments/assets/a18c5ba3-2f09-4819-87bc-860e47aba81b">
<img width="1493" alt="image" src="https://github.com/user-attachments/assets/6281a8e2-bfcb-4358-9ec0-a727e906caae">
<img width="522" alt="image" src="https://github.com/user-attachments/assets/8d3d4ef2-e431-4ba9-8a19-5bfc2173155b">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 127.0.6533.89

**Comment by adenvt** [comment]
should be fixed on 736e4baa17
