### ISSUE TITLE
Base: Navigation

### ISSUE THREAD

**Issue by avriq** [privy-open-source/design-system#169]
LINK FIGMA STYLEGUIDE

https://www.figma.com/file/tVQNwXeQkMtZlX1x3qjJu8/B-A-S-E-%2F-Style-Guide?node-id=262%3A2160

**Comment by sampahcoding** [comment]
note: navigation state left right blom ada
<img width="512" alt="Screen Shot 2022-10-06 at 11 18 13" src="https://user-images.githubusercontent.com/1254087/194212992-8beb270a-9ec7-4b2e-95f8-8aced5df755e.png">
