### ISSUE TITLE
VeeValidate integration: Error message appears on input mount

### ISSUE THREAD

**Issue by radyakaze** [privy-open-source/design-system#615]
**Describe the bug**
When integrating VeeValidate into my project, I noticed that the input component's status is set to "dirty" immediately upon mounting. As a result, the error message is displayed even though the input hasn't been modified. The expected behavior is for the error message to appear only if the input has been modified (dirty).

**To Reproduce**
1. Go to https://stackblitz.com/github/radyakaze/persona-veevalidate-bug?file=pages%2Findex.vue
2. Observe that the error message appears on input mount, even though the input hasn't been modified.

**Expected behavior**
The error message should only appear when the input has been modified (dirty), not immediately upon mounting the component.

**Screenshots**
<img width="1624" alt="image" src="https://github.com/privy-open-source/design-system/assets/3848643/fa94fee3-4b9b-4abe-a219-9a2721c2f4b4">

**Desktop (please complete the following information):**
 - OS: Any OS
 - Browser Any Browser
 - Version Any Version

**Smartphone (please complete the following information):**

**Comment by radyakaze** [comment]
Please note that this issue also occurs when using Vuelidate as an alternative to VeeValidate, indicating that it is not specific to a particular dependency but rather a common validation implementation issue in the input component.

**Comment by hendras1722** [comment]
Hi Sir you can change props v-bind to vBind
<img width="576" alt="image" src="https://github.com/privy-open-source/design-system/assets/57746184/908c19e9-5fb8-4846-9d8a-99dc9c432c15">

https://stackblitz.com/edit/github-bn78s5?file=pages%2Findex.vue
